### PR TITLE
nextTransitionTime & lastTransitionTime

### PR DESCRIPTION
**Pull request by jsuiker**
Just needed a bit more functionality... All tests are passing...

### CODE REVIEW

**Comment by aforty** [comment]
This is really useful to me as well. Can we get this in?

**Comment by lennym** [comment]
Thanks for adding this, and sorry it's taken me a bit of a while to look at.

I'm not a huge fan of the returning an object with a `moment` property, but I understand why you've done it that way.

If you could add a little documentation/example to the README then I'll happily merge and publish.

**Comment by jsuiker** [comment]
should be ready?

**Comment by lennym** [comment]
Thanks, will ship it now.

👍

**Comment by lennym** [comment]
Published v1.1.0

**Pull request merged**
