### PR TITLE
Typescript definitions file

### PR DESCRIPTION
**Pull request by Guria**
Hello. I wonder if you are ready to accept typing definitions to your repo.
Some refs: typings/typings#322 moment/moment#2916

### CODE REVIEW

**Comment by PatrickJS** [comment]
this will work for tsd but not typings

**Comment by PatrickJS** [comment]
nvm I thought this was the moment repo

**Comment by Guria** [comment]
Oh. Just found that MomentLanguge interface should be also extended.

**Comment by Guria** [comment]
Added `MomentLanguage` and chaged tab size to 4

**Comment by Guria** [comment]
Looks like it needs a little more signatures. I will add all when figure them out.

**Pull request closed without merging**
