### PR TITLE
handle adding many hours that span over weeks

### PR DESCRIPTION
**Pull request by mentheosis**
it will iterate more, but it will correctly add a large span of hours that crosses several periods of closure.

I didn't implement the subtraction equivalent yet because its late night now :/

### CODE REVIEW

**Comment by mentheosis** [comment]
by the way, 3 of the unit tests were already in a failed state when I started. The holiday unit tests seems to succeed on the auto-build below, but it fails on my local, any idea why?

3) moment.business-hours holidays does not include holidays when adding working time:

```
  AssertionError: expected '2015-02-26 17:00:00.000' to equal '2015-03-02 12:00:00.000'
  + expected - actual

  +"2015-03-02 12:00:00.000"
  -"2015-02-26 17:00:00.000"
```

thanks

**Comment by lennym** [comment]
Thanks for your input and the heads up on the failing tests. They were passing when I wrote it, but it looks like they're losing 3ms now, which is a little odd. Will investigate...

**Comment by lennym** [comment]
The two failing tests which end up 3ms out look like a regression moving between v2.9.0 and v2.10.2 of moment.

**Comment by lennym** [comment]
FYI - I have identified and fixed the issue with the pre-existing failing tests. All should be in order now.

https://github.com/lennym/moment-business-time/commit/85e94f399368db4057c3066cc5364bc093a777ec

**Comment by didil** [comment]
Should this be closed then ?

**Comment by lennym** [comment]
I'm not keen to merge half a fix. If someone can put together the equivalent for subtraction then I'll happily merge.

**Comment by mentheosis** [comment]
Oh I can fix up the subtraction part at some point too and update this. I also fixed another thing recently where passing in decimal value units can cause infinite loop, that can be included

**Comment by lennym** [comment]
@mentheosis That's really great. Thanks a lot. Apologies I don't have time to write the code myself.

One thing that would help me _a lot_ though is if you could provide the two bug fixes as separate PRs (especially if you have already fixed one).

**Comment by Guria** [comment]
ping all

**Comment by lennym** [comment]
I have ported the addition fixes here to subtraction and merged at #14

Thanks for your help @mentheosis

**Comment by lennym** [comment]
Published at v0.4.1

**Pull request closed without merging**
